groqai:
  model: "llama-3.3-70b-versatile"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

whisper_model:
  name: "base"
  device: "cpu"


logger:
  log_dir: "logs"


pdf_file:
  loc: "src/mysoft_rag/data/Mysoftheaven-Profile_2026.pdf"

web_data:
  urls: [
    "https://mysoftheaven.com/products",
    "https://mysoftheaven.com/notable_products",
    "https://mysoftheaven.com/notable_details/7",
    "https://mysoftheaven.com/notable_details/5",
    "https://mysoftheaven.com/company-profile",
    "https://mysoftheaven.com/ceo-message",
    "https://mysoftheaven.com/service/website-design-development",
    "https://mysoftheaven.com/service/web-application-development",
    "https://mysoftheaven.com/service/machine-learning",
    "https://mysoftheaven.com/management-team",
    "https://mysoftheaven.com/"
  ]

vector_database:
  loc: "vector_database"