groqai:
  model: "llama-3.3-70b-versatile"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

whisper_model:
  name: "base"
  device: "cpu"


logger:
  log_dir: "logs"


pdf_file:
  loc: "src/mysoft_rag/data/Hands_On_Machine_Learning_with_Scikit_Learn_and_TensorFlow.pdf"

web_data:
  urls: [
    "https://en.wikipedia.org/wiki/Machine_learning",
  ]

vector_database:
  loc: "vector_database"