groqai:
  model: "llama-3.3-70b-versatile"
  embedding_model: "l3cube-pune/bengali-sentence-similarity-sbert"
  temperature: 0.0

whisper_model:
  name: "base"
  device: "cpu"


logger:
  log_dir: "logs"


pdf_file:
  loc: "src/mysoft_rag/data/as_sunnah_fqa.pdf"

web_data:
  urls: [
    "https://en.wikipedia.org/wiki/Machine_learning",
  ]

vector_database:
  loc: "vector_database"